# Generated by Django 3.2.5 on 2021-07-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.CharField(max_length=200, verbose_name='Преимущество')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('telephone', models.CharField(blank=True, max_length=10, verbose_name='Номер телефона (без "+38")')),
                ('description', models.TextField(blank=True, verbose_name='Заметка о клиенте')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Дата регистрации клиента')),
                ('activity', models.CharField(blank=True, max_length=50, verbose_name='Род деятельности')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя дизайна')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='photo/designs/%Y/%m/%d', verbose_name='Фото')),
                ('design_date', models.DateField(auto_now=True, verbose_name='Дата добавления дизайна')),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайны ногтей',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('telephone', models.CharField(blank=True, max_length=10, verbose_name='Номер телефона без "+38"')),
                ('photo', models.ImageField(blank=True, upload_to='photos/masters', verbose_name='Фото мастера')),
                ('about', models.TextField(blank=True, verbose_name='Информация о мастере')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тип материала')),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_published', models.BooleanField(verbose_name='Опубликовано')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='photos/blog', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(default='', max_length=200, verbose_name='Кому принадлежит')),
                ('content', models.TextField(verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Наименование услуги')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('is_published', models.BooleanField(verbose_name='Показывать в прайсе услуг')),
                ('header', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Имя тега')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True, verbose_name='Дата визита')),
                ('info', models.TextField(blank=True, verbose_name='Заметка о визите')),
                ('price', models.CharField(blank=True, max_length=4, verbose_name='Стоимость работ')),
                ('completed', models.BooleanField(verbose_name='Состоялся ли визит')),
                ('visit_cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина отмены визита')),
                ('photo_before', models.ImageField(blank=True, upload_to='photos/visits/before/%Y/%m/%d', verbose_name='Фото до')),
                ('photo_after', models.ImageField(blank=True, upload_to='photos/visits/after/%Y/%m/%d', verbose_name='Фото после')),
                ('is_published', models.BooleanField(default=False, verbose_name='Показывать в портфолио')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.client', verbose_name='Клиент')),
                ('designs', models.ManyToManyField(blank=True, to='services.Design', verbose_name='Дизайн')),
                ('tags', models.ManyToManyField(blank=True, to='services.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('price', models.CharField(blank=True, max_length=4, verbose_name='Стоимость')),
                ('rating', models.IntegerField(blank=True, default='0', verbose_name='Качество материала')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.materialtype')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(blank=True, to='services.Material'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сертификат')),
                ('data', models.CharField(blank=True, max_length=80, verbose_name='Когда выдан')),
                ('school', models.CharField(blank=True, max_length=80, verbose_name='Школа маникюра')),
                ('photo', models.ImageField(blank=True, upload_to='photos/certificates', verbose_name='Сертификат')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.master', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
