# Generated by Django 3.2 on 2021-06-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_visit',
            new_name='registration_date',
        ),
    ]
