# Generated by Django 3.2 on 2021-06-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_first_visit_client_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/designs/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.CharField(blank=True, max_length=4, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='material',
            name='rating',
            field=models.IntegerField(blank=True, default='0', verbose_name='Качество материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название материала'),
        ),
    ]
