# Generated by Django 3.2 on 2021-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210628_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_date',
            field=models.DateField(auto_now=True, verbose_name='Дата добавления дизайна'),
        ),
    ]
