# Generated by Django 3.2 on 2021-06-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_design_design_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='info',
            field=models.TextField(blank=True, verbose_name='Заметка о визите'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='designs',
            field=models.ManyToManyField(blank=True, to='services.Design'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='price',
            field=models.CharField(blank=True, max_length=4, verbose_name='Стоимость работ'),
        ),
    ]
