# Generated by Django 3.2 on 2021-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210628_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Наименование услуги'),
        ),
    ]
