# Generated by Django 3.2 on 2021-06-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='photo_after',
            field=models.ImageField(blank=True, upload_to='photo/before_after/%Y/%m/%d', verbose_name='Фото после'),
        ),
        migrations.AddField(
            model_name='visit',
            name='photo_before',
            field=models.ImageField(blank=True, upload_to='photo/before_after/%Y/%m/%d', verbose_name='Фото до'),
        ),
    ]
