# Generated by Django 3.2 on 2021-06-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20210629_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='photo_after',
            field=models.ImageField(blank=True, upload_to='photos/visits/after/%Y/%m/%d', verbose_name='Фото после'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='photo_before',
            field=models.ImageField(blank=True, upload_to='photos/visits/before/%Y/%m/%d', verbose_name='Фото до'),
        ),
    ]
