# Generated by Django 3.2 on 2021-06-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210629_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Показывать в портфолио'),
        ),
    ]
