# Generated by Django 3.2 on 2021-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_visit_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Имя тега')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='services.Tag'),
        ),
    ]
