# Generated by Django 3.2 on 2021-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20210629_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Диплом')),
                ('data', models.CharField(max_length=80, verbose_name='Когда выдан')),
                ('school', models.CharField(max_length=80, verbose_name='Школа маникюра')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
            },
        ),
        migrations.AlterField(
            model_name='visit',
            name='designs',
            field=models.ManyToManyField(blank=True, to='services.Design', verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='services.Tag', verbose_name='Теги'),
        ),
    ]
