# Generated by Django 3.2 on 2021-07-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20210703_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/certificates', verbose_name='Сертификат'),
        ),
    ]
