# Generated by Django 3.2 on 2021-07-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20210703_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='header',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='master',
            name='about',
            field=models.TextField(blank=True, verbose_name='Информация о мастере'),
        ),
    ]
