# Generated by Django 3.2 on 2021-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='speaker',
            field=models.CharField(default='', max_length=200, verbose_name='Кому принадлежит'),
        ),
    ]
