# Generated by Django 3.2 on 2021-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(verbose_name='Опубликовано'),
        ),
    ]
