# Generated by Django 3.2 on 2021-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/blog', verbose_name='Фото'),
        ),
    ]
